version: '3'
services:
  php:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/app:cached
    links:
      - mysql

  nginx:
    image: nginx:1.16
    volumes:
      - ${PWD}:/app:cached
      - ${PWD}/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    ports:
      - 80:80
      - 443:443
    links:
      - php

  mysql:
    image: mysql:5.7.26
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: pass
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ${PWD}/docker/mysql:/var/lib/mysql:cached
